FROM python:3.10-slim
WORKDIR /app

RUN pip install --no-cache-dir uv
ENV UV_SYSTEM_PYTHON=1

COPY fastapi_app/pyproject.toml fastapi_app/uv.lock /app/fastapi_app/
RUN uv sync --project /app/fastapi_app --no-dev --frozen

COPY . .
WORKDIR /app/fastapi_app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
